### ISSUE TITLE
Build the API

### ISSUE THREAD

**Issue by chriswhong** [BetaNYC/budgetBuddy#3]
Ideas are in /apiCalls.txt

Heroku app?  What database?  What backend framework?  

Should we allow for CSV and JSON results?

**Comment by volkanunsal** [comment]
I remembered that I built almost exactly the same thing (an API adapter) for [the city's 311 dataset last year](http://open311.herokuapp.com/). It allows you to query the city data using the Open311 endpoints –– well only one endpoint because that's all I had time for. The framework is Express.js and it's already implementing much of the functionality we want in this API. I can literally just drop that into this project, and swap out the backend, and it would work. 

In addition, it's also implementing one of the most important features that an API adapter needs to have: streaming output. That is to say, it should start sending the data as soon as it starts receiving it, rather than waiting for the entire JSON to finish. This is a hard problem for Ruby and other languages I looked at because they didn't allow streaming output as I recall (only buffered output). That's why I chose Express.js, so that I could use Node's streaming capabilities. It wasn't easy to implement this, but it's in the app, too.

**Comment by chriswhong** [comment]
+1 for express.js. we used it as part of the mean stack on our tax map
project.

**Comment by chriswhong** [comment]
Also I will be able to contribute more if we use node.

**Comment by volkanunsal** [comment]
I added my code in the server directory. It might be a bit crufty because it used to have HTML pages, as well. I will try to whittle it down to shape in the coming days.

**Comment by chriswhong** [comment]
Hi all, tonight I assembled a new node server with a single working API call in the db-included branch in a new directory /server2
http://localhost:3000/api/v1/2015/op/summary 
returns an array of agency summarized data (agency_id, agency_name, sum(value)).

It's extremely rudimentary and uses express.js and the sqlite3 package.  Give it a whirl and let me know what you think.

**Comment by volkanunsal** [comment]
Rather than writing raw SQL, I propose we can find out if there is a robust
ORM that can plug in the user inputs in a safe way. I haven't explored the
ORM landscape on Node much, so if anyone wants to find one that works, that
would be awesome.

On Tue, Jun 24, 2014 at 11:16 PM, chriswhong notifications@github.com
wrote:

> Hi all, tonight I assembled a new node server with a single working API
> call in the db-included branch.
> 
> http://localhost:3000/api/v1/2015/op/summary
> returns an array of agency summarized data (agency_id, agency_name,
> sum(value)).
> 
> It's extremely rudimentary and uses express.js and the sqlite3 package.
> Give it a whirl and let me know what you think.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BetaNYC/budgetBuddy/issues/3#issuecomment-47056481.

## 

_Volkan Unsal_
_web and mobile development_
volkanunsal.com http://bit.ly/1h1ebjy

**Comment by chriswhong** [comment]
Do you mean something that converts the parameters passed in the URL and
spits out a SQL query based on some logic?

**Comment by volkanunsal** [comment]
Yes, it converts and sanitizes user input so we don't fail the Little Bobby
Tables (relevant XKCD reference.)

On Wed, Jun 25, 2014 at 8:23 AM, chriswhong notifications@github.com
wrote:

> Do you mean something that converts the parameters passed in the URL and
> spits out a SQL query based on some logic?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BetaNYC/budgetBuddy/issues/3#issuecomment-47093697.

## 

_Volkan Unsal_
_web and mobile development_
volkanunsal.com http://bit.ly/1h1ebjy

**Comment by chriswhong** [comment]
Oh cool... I have no idea where to start on that, but if it's the right
thing to do, let's do it.

Yes, I had to look this up: http://xkcd.com/327/

-C

**Comment by volkanunsal** [comment]
The API is up and running at http://budgetbuddy.herokuapp.com.
